### ISSUE TITLE
New repo

### ISSUE THREAD

**Issue by kartsims** [nicoles/mbk_footprints#4]
hey @nicoles whenever you see this, it'd be appreciated if you could direct people to the [new repo](https://github.com/FKcaps/mbk-footprints) that's been moved to a new github org, so that I could update it myself. I tried to contact you to move this repo with no luck 😢

**Comment by nicoles** [comment]
Apologies, all of my github mail has been going to spam! Makes sense for you to maintain tho~ I'll link to it from mine.

**Comment by nicoles** [comment]
Updated readme with link

**Comment by kartsims** [comment]
oh thank you @nicoles 🙏 have a good day!
